[2025-03-25T14:33:20.976+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [queued]>
[2025-03-25T14:33:20.995+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [queued]>
[2025-03-25T14:33:20.997+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-25T14:33:21.024+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): creare1> on 2025-03-24 03:00:00+00:00
[2025-03-25T14:33:21.044+0000] {standard_task_runner.py:57} INFO - Started process 456 to run task
[2025-03-25T14:33:21.051+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'passanger_traffic', 'creare1', 'scheduled__2025-03-24T03:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/passenger_traffic_dag.py', '--cfg-path', '/tmp/tmpd5td88ou']
[2025-03-25T14:33:21.056+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask creare1
[2025-03-25T14:33:21.089+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-25T14:33:21.221+0000] {task_command.py:415} INFO - Running <TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [running]> on host 55005b7b65eb
[2025-03-25T14:33:21.451+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='passanger_traffic' AIRFLOW_CTX_TASK_ID='creare1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-24T03:00:00+00:00'
[2025-03-25T14:33:21.454+0000] {sql.py:274} INFO - Executing: 
    CREATE SCHEMA IF NOT EXISTS presentation;
[2025-03-25T14:33:21.489+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-25T14:33:21.514+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-25T14:33:21.536+0000] {sql.py:418} INFO - Running statement: 
    CREATE SCHEMA IF NOT EXISTS presentation;, parameters: None
[2025-03-25T14:33:21.571+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=passanger_traffic, task_id=creare1, execution_date=20250324T030000, start_date=20250325T143320, end_date=20250325T143321
[2025-03-25T14:33:21.643+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-25T14:33:21.714+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-25T15:13:00.573+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [queued]>
[2025-03-25T15:13:00.598+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [queued]>
[2025-03-25T15:13:00.600+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-25T15:13:00.636+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): creare1> on 2025-03-24 03:00:00+00:00
[2025-03-25T15:13:00.656+0000] {standard_task_runner.py:57} INFO - Started process 239 to run task
[2025-03-25T15:13:00.674+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'passanger_traffic', 'creare1', 'scheduled__2025-03-24T03:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/passenger_traffic_dag.py', '--cfg-path', '/tmp/tmp_p65y8z1']
[2025-03-25T15:13:00.688+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask creare1
[2025-03-25T15:13:00.729+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-25T15:13:00.834+0000] {task_command.py:415} INFO - Running <TaskInstance: passanger_traffic.creare1 scheduled__2025-03-24T03:00:00+00:00 [running]> on host f489f841bffe
[2025-03-25T15:13:01.018+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='passanger_traffic' AIRFLOW_CTX_TASK_ID='creare1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-24T03:00:00+00:00'
[2025-03-25T15:13:01.021+0000] {sql.py:274} INFO - Executing: 
    CREATE SCHEMA IF NOT EXISTS presentation;
[2025-03-25T15:13:01.037+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-25T15:13:01.051+0000] {base.py:73} INFO - Using connection ID '***_dwh' for task execution.
[2025-03-25T15:13:01.072+0000] {sql.py:418} INFO - Running statement: 
    CREATE SCHEMA IF NOT EXISTS presentation;, parameters: None
[2025-03-25T15:13:01.087+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=passanger_traffic, task_id=creare1, execution_date=20250324T030000, start_date=20250325T151300, end_date=20250325T151301
[2025-03-25T15:13:01.147+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-25T15:13:01.196+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
